-- solveit_db.lecturers definition

CREATE TABLE `lecturers` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(191) NOT NULL,
  `email` varchar(191) NOT NULL,
  `phone` varchar(191) NOT NULL,
  `avatar` varchar(191) DEFAULT NULL,
  `interests` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `dob` date DEFAULT NULL,
  `gender` varchar(191) NOT NULL,
  `school_id` int unsigned NOT NULL,
  `faculty_id` int unsigned NOT NULL,
  `department_id` int unsigned DEFAULT NULL,
  `balance` varchar(191) NOT NULL DEFAULT '0',
  `affiliate_balance` varchar(191) NOT NULL DEFAULT '0',
  `bank_information` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `permissions` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `email_verified` varchar(191) DEFAULT NULL,
  `phone_verified` tinyint(1) NOT NULL DEFAULT '0',
  `face_id` varchar(191) DEFAULT NULL,
  `face_verified` tinyint(1) NOT NULL DEFAULT '0',
  `id_verification` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `id_verified` tinyint(1) NOT NULL DEFAULT '0',
  `user_id` int unsigned DEFAULT NULL,
  `staff_id` int unsigned DEFAULT NULL,
  `student_id` int unsigned DEFAULT NULL,
  `lecturer_id` int unsigned DEFAULT NULL,
  `last_login` datetime DEFAULT NULL,
  `send_next_otp_sms_after` datetime DEFAULT NULL,
  `next_school_data_update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `core_service_earning_times` int NOT NULL DEFAULT '0',
  `password_reset_code` varchar(191) DEFAULT NULL,
  `online` varchar(191) DEFAULT 'online',
  `type` varchar(191) NOT NULL DEFAULT 'lecturer',
  `code` varchar(191) NOT NULL,
  `password` varchar(191) NOT NULL,
  `dfsdasdeder` text,
  `remember_token` varchar(100) DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `lecturers_email_unique` (`email`),
  UNIQUE KEY `lecturers_phone_unique` (`phone`),
  UNIQUE KEY `lecturers_code_unique` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;